apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app 
spec:
  selector:
    matchLabels:
      run: python 
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx 
    spec:
      containers:
      - name: python 
        image: 372045710271.dkr.ecr.us-east-1.amazonaws.com/python-demo
        ports: 
        - containerPort: 8080
